### PR TITLE
Release docker image for arm64

### PR DESCRIPTION
**Pull request by odidev**
The following file has been created :
Added .travis.yml file to build and push the image for both amd64 and arm64 platforms.

### CODE REVIEW

**Comment by odidev** [comment]
@byrnedo Could you please review this PR.

**Review by byrnedo — APPROVED** [review]
Nice

**Comment by odidev** [comment]
@byrnedo Thanks for merging the PR. May I know when are you planning on releasing the images?

**Comment by abhisheknishant138** [comment]
May I know when are you planning on releasing the images for arm64.

**Comment by odidev** [comment]
May I know when are you planning on releasing the images for arm64.

**Comment by byrnedo** [comment]
@odidev up on docker hub now

**Pull request merged**
